---
version: '3'
    
services:
  mariadb:
    image: mariadb
    # container_name: mariadb
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "juve"
      MYSQL_DATABASE: "exo3"
      MYSQL_USER: "delpiero"
      MYSQL_PASSWORD: "juve"
 
  flaskapp:
    build: .
    image: anassteroufi/flask-web
    links: 
    - mariadb
    # depends_on:
    # - mariadb
    # environment:
    #   MYSQL_ROOT_PASSWORD: "juve"
    #   MYSQL_DATABASE: "exo3"    
    ports:
      - "5000:5000"
    # restart: always

volumes:
  db_data: {}