---
apiVersion: v1
kind: Namespace
metadata:
  name: exo3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo3-deploy
  namespace: exo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exo3
  template:
    metadata:
      labels:
        app: exo3
    spec:
      containers:
      - name: flaskapp
        image: anassteroufi/flask-web:1.0.0
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5000
      - name: mariadbapp
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: juve
        volumeMounts:
        - name: mariadb-volume
          mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  name: exo3-svc
  namespace: exo3
spec:
  type: NodePort
  selector:
    app: exo3
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32702
    protocol: TCP


